## 1. Imports & Setup

In [3]:
import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns',None)

## 2. Load Data

In [4]:
BASE_DIR = os.path.abspath("..")
DATA_PATH = os.path.join(BASE_DIR, "data", "raw")

df1 = pd.read_excel(os.path.join(DATA_PATH, "case_study1.xlsx"))
df2 = pd.read_excel(os.path.join(DATA_PATH, "case_study2.xlsx"))

In [5]:
df1.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,Tot_TL_closed_L12M,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,Auto_TL,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,0,0,0.00,0.0,0,0,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,1,0,1.00,0.0,0,0,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,2,0,0.25,0.0,1,1,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,1,0,1.00,0.0,1,0,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,0,0,0.00,0.0,0,1,0,0,0,0,0,3,0,2,131,32

In [6]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,max_deliq_6mts,max_deliq_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,num_std_6mts,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_6mts,num_dbt_12mts,num_lss,num_lss_6mts,num_lss_12mts,recent_level_of_deliq,tot_enq,CC_enq,CC_enq_L6m,CC_enq_L12m,PL_enq,PL_enq_L6m,PL_enq_L12m,time_since_recent_enq,enq_L12m,enq_L6m,enq_L3m,MARITALSTATUS,EDUCATION,AGE,GENDER,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_of_active_TLs_ever,pct_opened_TLs_L6m_of_L12m,pct_currentBal_all_TL,CC_utilization,CC_Flag,PL_utilization,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,-99999,-99999,0,0,21,5,11,0,0,0,0,0,0,0,0,0,29,6,0,0,0,6,0,0,566,0,0,0,Married,12TH,48,M,51000,114,0.200,0.0,0.798,-99999.0,0,0.798,1,0.0,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,209,1,0,0,Single,GRADUATE,23,F,19000,50,1.000,0.0,0.370,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,25,25,0,0,10,5,10,0,0,0,0,0,0,0,0,0,25,4,0,0,0,0,0,0,587,0,0,0,Married,SSC,40,M,18,191,1.000,0.5,0.585,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,-99999,-99999,0,0,5,4,5,0,0,0,0,0,0,0,0,0,0,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,Married,SSC,34,M,10000,246,1.000,1.0,0.990,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,-99999,-99999,0,0,53,4,16,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3951,0,0,0,Married,POST-GRADUATE,48,M,15000,75,0.333,0.0,0.000,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

In [7]:
print(df1.shape)
print(df2.shape)

(51336, 26)
(51336, 62)

## 3. Data Cleaning

In [8]:
print(df1.isnull().sum().sum())
print(df2.isnull().sum().sum())

0
0

In [9]:
df1=df1[df1['Age_Oldest_TL'] != -99999]

In [10]:
print(df1.shape)

(51296, 26)

In [11]:
columns_to_removed=[]

In [12]:
for i in df2.columns:
    count=(df2[i]==-99999).sum()
    percentage=(count/len(df2))*100
    if count > 0:
        print(f"Column: {i}, Count: {count}, Percentage: {percentage:.2f}%")

Column: time_since_recent_payment, Count: 4291, Percentage: 8.36%
Column: time_since_first_deliquency, Count: 35949, Percentage: 70.03%
Column: time_since_recent_deliquency, Count: 35949, Percentage: 70.03%
Column: max_delinquency_level, Count: 35949, Percentage: 70.03%
Column: max_deliq_6mts, Count: 12890, Percentage: 25.11%
Column: max_deliq_12mts, Count: 10832, Percentage: 21.10%
Column: tot_enq, Count: 6321, Percentage: 12.31%
Column: CC_enq, Count: 6321, Percentage: 12.31%
Column: CC_enq_L6m, Count: 6321, Percentage: 12.31%
Column: CC_enq_L12m, Count: 6321, Percentage: 12.31%
Column: PL_enq, Count: 6321, Percentage: 12.31%
Column: PL_enq_L6m, Count: 6321, Percentage: 12.31%
Column: PL_enq_L12m, Count: 6321, Percentage: 12.31%
Column: time_since_recent_enq, Count: 6321, Percentage: 12.31%
Column: enq_L12m, Count: 6321, Percentage: 12.31%
Column: enq_L6m, Count: 6321, Percentage: 12.31%
Column: enq_L3m, Count: 6321, Percentage: 12.31%
Column: pct_currentBal_all_TL, Count: 72, Percentage: 0.14%
Column: CC_utilization, Count: 47636, Percentage: 92.79%
Column: PL_utilization, Count: 44435, Percentage: 86.56%
Column: max_unsec_exposure_inPct, Count: 23178, Percentage: 45.15%

In [13]:
for i in df2.columns:
    if (df2[i]==-99999).sum()>10000:
        columns_to_removed.append(i)
        print(i)

time_since_first_deliquency
time_since_recent_deliquency
max_delinquency_level
max_deliq_6mts
max_deliq_12mts
CC_utilization
PL_utilization
max_unsec_exposure_inPct

In [14]:
columns_to_removed

['time_since_first_deliquency',
 'time_since_recent_deliquency',
 'max_delinquency_level',
 'max_deliq_6mts',
 'max_deliq_12mts',
 'CC_utilization',
 'PL_utilization',
 'max_unsec_exposure_inPct']

In [15]:
df2=df2.drop(columns=columns_to_removed)

In [16]:
df2.shape

(51336, 54)

In [18]:
# check again for -99999 in df2
for i in df2.columns:
    count=(df2[i]==-99999).sum()
    percentage=(count/len(df2))*100
    if count > 0:
        print(f"Column: {i}, Count: {count}, Percentage: {percentage:.2f}%")

Column: time_since_recent_payment, Count: 4291, Percentage: 8.36%
Column: tot_enq, Count: 6321, Percentage: 12.31%
Column: CC_enq, Count: 6321, Percentage: 12.31%
Column: CC_enq_L6m, Count: 6321, Percentage: 12.31%
Column: CC_enq_L12m, Count: 6321, Percentage: 12.31%
Column: PL_enq, Count: 6321, Percentage: 12.31%
Column: PL_enq_L6m, Count: 6321, Percentage: 12.31%
Column: PL_enq_L12m, Count: 6321, Percentage: 12.31%
Column: time_since_recent_enq, Count: 6321, Percentage: 12.31%
Column: enq_L12m, Count: 6321, Percentage: 12.31%
Column: enq_L6m, Count: 6321, Percentage: 12.31%
Column: enq_L3m, Count: 6321, Percentage: 12.31%
Column: pct_currentBal_all_TL, Count: 72, Percentage: 0.14%

In [20]:
# columns to be treated for placeholder
columns_treated=[]

In [21]:
for i in df2.columns:
    count=(df2[i]==-99999).sum()
    percentage=(count/len(df2))*100
    if count > 0:
        print(f"Column: {i}, Count: {count}, Percentage: {percentage:.2f}%")
        columns_treated.append(i)

Column: time_since_recent_payment, Count: 4291, Percentage: 8.36%
Column: tot_enq, Count: 6321, Percentage: 12.31%
Column: CC_enq, Count: 6321, Percentage: 12.31%
Column: CC_enq_L6m, Count: 6321, Percentage: 12.31%
Column: CC_enq_L12m, Count: 6321, Percentage: 12.31%
Column: PL_enq, Count: 6321, Percentage: 12.31%
Column: PL_enq_L6m, Count: 6321, Percentage: 12.31%
Column: PL_enq_L12m, Count: 6321, Percentage: 12.31%
Column: time_since_recent_enq, Count: 6321, Percentage: 12.31%
Column: enq_L12m, Count: 6321, Percentage: 12.31%
Column: enq_L6m, Count: 6321, Percentage: 12.31%
Column: enq_L3m, Count: 6321, Percentage: 12.31%
Column: pct_currentBal_all_TL, Count: 72, Percentage: 0.14%

In [22]:
columns_treated

['time_since_recent_payment',
 'tot_enq',
 'CC_enq',
 'CC_enq_L6m',
 'CC_enq_L12m',
 'PL_enq',
 'PL_enq_L6m',
 'PL_enq_L12m',
 'time_since_recent_enq',
 'enq_L12m',
 'enq_L6m',
 'enq_L3m',
 'pct_currentBal_all_TL']

In [26]:
for i in df2.columns:
    for j in columns_treated:
        if i==j:
            print(df2[j].head(5))

0      549
1       47
2      302
3   -99999
4      583
Name: time_since_recent_payment, dtype: int64
0        6
1        1
2        4
3   -99999
4        1
Name: tot_enq, dtype: int64
0        0
1        0
2        0
3   -99999
4        0
Name: CC_enq, dtype: int64
0        0
1        0
2        0
3   -99999
4        0
Name: CC_enq_L6m, dtype: int64
0        0
1        0
2        0
3   -99999
4        0
Name: CC_enq_L12m, dtype: int64
0        6
1        0
2        0
3   -99999
4        0
Name: PL_enq, dtype: int64
0        0
1        0
2        0
3   -99999
4        0
Name: PL_enq_L6m, dtype: int64
0        0
1        0
2        0
3   -99999
4        0
Name: PL_enq_L12m, dtype: int64
0      566
1      209
2      587
3   -99999
4     3951
Name: time_since_recent_enq, dtype: int64
0        0
1        1
2        0
3   -99999
4        0
Name: enq_L12m, dtype: int64
0        0
1        0
2        0
3   -99999
4        0
Name: enq_L6m, dtype: int64
0        0
1        0
2        0
3   -99999
4        0
Name: enq_L3m, dtype: int64
0    0.798
1    0.370
2    0.585
3    0.990
4    0.000
Name: pct_currentBal_all_TL, dtype: float64

In [27]:
def treat_columns(df, columns_treated):
    import numpy as np
    
    time_cols = ['time_since_recent_payment', 'time_since_recent_enq']
    ratio_cols = ['pct_currentBal_all_TL']
    count_cols = [col for col in columns_treated if col not in time_cols + ratio_cols]
    
    df[columns_treated] = df[columns_treated].replace(-99999, np.nan)
    
    for col in time_cols:
        df[col + "_missing"] = df[col].isna().astype(int)
        df[col] = df[col].fillna(df[col].max() + 1)
    
    df[count_cols] = df[count_cols].fillna(0)
    
    for col in ratio_cols:
        df[col].fillna(df[col].median(), inplace=True)
    
    return df

In [28]:
treat_columns(df2,columns_treated)

,PROSPECTID,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,num_std_6mts,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_6mts,num_dbt_12mts,num_lss,num_lss_6mts,num_lss_12mts,recent_level_of_deliq,tot_enq,CC_enq,CC_enq_L6m,CC_enq_L12m,PL_enq,PL_enq_L6m,PL_enq_L12m,time_since_recent_enq,enq_L12m,enq_L6m,enq_L3m,MARITALSTATUS,EDUCATION,AGE,GENDER,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_of_active_TLs_ever,pct_opened_TLs_L6m_of_L12m,pct_currentBal_all_TL,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag,time_since_recent_payment_missing,time_since_recent_enq_missing
0,1,549.0,11,29,0,0,0,0,0,21,5,11,0,0,0,0,0,0,0,0,0,29,6.0,0.0,0.0,0.0,6.0,0.0,0.0,566.0,0.0,0.0,0.0,Married,12TH,48,M,51000,114,0.200,0.0,0.798,0,1,0.0,0.0,0.0,0.0,1,0,PL,PL,696,P2,0,0
1,2,47.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,209.0,1.0,0.0,0.0,Single,GRADUATE,23,F,19000,50,1.000,0.0,0.370,0,0,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2,0,0
2,3,302.0,9,25,1,9,8,0,0,10,5,10,0,0,0,0,0,0,0,0,0,25,4.0,0.0,0.0,0.0,0.0,0.0,0.0,587.0,0.0,0.0,0.0,Married,SSC,40,M,18,191,1.000,0.5,0.585,0,0,0.0,0.0,0.0,0.0,1,0,ConsumerLoan,others,693,P2,0,0
3,4,6066.0,0,0,0,0,0,0,0,5,4,5,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4769.0,0.0,0.0,0.0,Married,SSC,34,M,10000,246,1.000,1.0,0.990,0,0,0.0,0.0,0.0,0.0,0,0,others,others,673,P2,1,1
4,5,583.0,0,0,0,0,0,0,0,53,4,16,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3951.0,0.0,0.0,0.0,Married,POST-GRADUATE,48,M,15000,75,0.333,0.0,0.000,0,0,0.0,0.0,0.0,0.0,0,0,AL,AL,753,P1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15.0,2,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,1.0,Married,12TH,43,M,18500,249,1.000,1.0,0.230,0,0,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4,0,0
51332,51333,57.0,0,0,0,0,0,0,0,6,4,6,0,0,0,0,0,0,0,0,0,0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,203.0,1.0,0.0,0.0,Married,SSC,31,M,25000,186,0.500,0.0,0.660,0,0,0.0,0.0,0.0,0.0,0,0,others,others,702,P1,0,0
51333,51334,32.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.0,0.0,0.0,0.0,2.0,2.0,2.0,1.0,5.0,4.0,2.0,Married,SSC,28,M,18000,66,0.500,0.5,0.428,0,0,1.0,0.0,1.0,0.0,0,0,ConsumerLoan,others,661,P3,0,0
51334,51335,58.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,242.0,1.0,0.0,0.0,Single,UNDER GRADUATE,25,F,12802,54,0.500,0.0,0.143,0,0,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,others,686,P2,0,0
51335,51336,74.0,0,0,0,0,0,0,0,18,4,10,0,0,0,0,0,0,0,0,0,0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,1.0,1.0,1.0,Married,SSC,25,M,16000,102,1.000,0.0,0.333,0,0,0.0,0.0,0.0,0.0,0,0,others,others,681,P2,0,0

In [29]:
# check again for -99999 in df2
for i in df2.columns:
    count=(df2[i]==-99999).sum()
    percentage=(count/len(df2))*100
    if count > 0:
        print(f"Column: {i}, Count: {count}, Percentage: {percentage:.2f}%")

In [30]:
# check for common column so that we can merge the df1 and df2
common_columns = set(df1.columns).intersection(set(df2.columns))
print("Common Columns:", common_columns)

Common Columns: {'PROSPECTID'}

In [31]:
df=pd.merge(df1,df2,how='inner',on='PROSPECTID')

In [32]:
df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,Tot_TL_closed_L12M,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,Auto_TL,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,num_std_6mts,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_6mts,num_dbt_12mts,num_lss,num_lss_6mts,num_lss_12mts,recent_level_of_deliq,tot_enq,CC_enq,CC_enq_L6m,CC_enq_L12m,PL_enq,PL_enq_L6m,PL_enq_L12m,time_since_recent_enq,enq_L12m,enq_L6m,enq_L3m,MARITALSTATUS,EDUCATION,AGE,GENDER,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_of_active_TLs_ever,pct_opened_TLs_L6m_of_L12m,pct_currentBal_all_TL,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag,time_since_recent_payment_missing,time_since_recent_enq_missing
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,0,0,0.00,0.0,0,0,0,0,1,0,4,1,4,0,72,18,549.0,11,29,0,0,0,0,0,21,5,11,0,0,0,0,0,0,0,0,0,29,6.0,0.0,0.0,0.0,6.0,0.0,0.0,566.0,0.0,0.0,0.0,Married,12TH,48,M,51000,114,0.200,0.0,0.798,0,1,0.0,0.0,0.0,0.0,1,0,PL,PL,696,P2,0,0
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,1,0,1.00,0.0,0,0,0,1,0,0,0,0,1,0,7,7,47.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,209.0,1.0,0.0,0.0,Single,GRADUATE,23,F,19000,50,1.000,0.0,0.370,0,0,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2,0,0
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,2,0,0.25,0.0,1,1,0,6,1,0,0,2,6,0,47,2,302.0,9,25,1,9,8,0,0,10,5,10,0,0,0,0,0,0,0,0,0,25,4.0,0.0,0.0,0.0,0.0,0.0,0.0,587.0,0.0,0.0,0.0,Married,SSC,40,M,18,191,1.000,0.5,0.585,0,0,0.0,0.0,0.0,0.0,1,0,ConsumerLoan,others,693,P2,0,0
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,1,0,1.00,0.0,1,0,0,0,0,0,0,0,1,1,5,5,6066.0,0,0,0,0,0,0,0,5,4,5,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4769.0,0.0,0.0,0.0,Married,SSC,34,M,10000,246,1.000,1.0,0.990,0,0,0.0,0.0,0.0,0.0,0,0,others,others,673,P2,1,1
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,0,0,0.00,0.0,0,1,0,0,0,0,0,3,0,2,131,32,583.0,0,0,0,0,0,0,0,53,4,16,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3951.0,0.0,0.0,0.0,Married,POST-GRADUATE,48,M,15000,75,0.333,0.0,0.000,0,0,0.0,0.0,0.0,0.0,0,0,AL,AL,753,P1,0,0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51296 entries, 0 to 51295
Data columns (total 81 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   PROSPECTID                         51296 non-null  int64
 1   Total_TL                           51296 non-null  int64
 2   Tot_Closed_TL                      51296 non-null  int64
 3   Tot_Active_TL                      51296 non-null  int64
 4   Total_TL_opened_L6M                51296 non-null  int64
 5   Tot_TL_closed_L6M                  51296 non-null  int64
 6   pct_tl_open_L6M                    51296 non-null  float64
 7   pct_tl_closed_L6M                  51296 non-null  float64
 8   pct_active_tl                      51296 non-null  float64
 9   pct_closed_tl                      51296 non-null  float64
 10  Total_TL_opened_L12M               51296 non-null  int64
 11  Tot_TL_closed_L12M                 51296 non-null  int64
 12  pct_tl_open_L12M                   51296 non-null  float64
 13  pct_tl_closed_L12M                 51296 non-null  float64
 14  Tot_Missed_Pmnt                    51296 non-null  int64
 15  Auto_TL                            51296 non-null  int64
 16  CC_TL                              51296 non-null  int64
 17  Consumer_TL                        51296 non-null  int64
 18  Gold_TL                            51296 non-null  int64
 19  Home_TL                            51296 non-null  int64
 20  PL_TL                              51296 non-null  int64
 21  Secured_TL                         51296 non-null  int64
 22  Unsecured_TL                       51296 non-null  int64
 23  Other_TL                           51296 non-null  int64
 24  Age_Oldest_TL                      51296 non-null  int64
 25  Age_Newest_TL                      51296 non-null  int64
 26  time_since_recent_payment          51296 non-null  float64
 27  num_times_delinquent               51296 non-null  int64
 28  max_recent_level_of_deliq          51296 non-null  int64
 29  num_deliq_6mts                     51296 non-null  int64
 30  num_deliq_12mts                    51296 non-null  int64
 31  num_deliq_6_12mts                  51296 non-null  int64
 32  num_times_30p_dpd                  51296 non-null  int64
 33  num_times_60p_dpd                  51296 non-null  int64
 34  num_std                            51296 non-null  int64
 35  num_std_6mts                       51296 non-null  int64
 36  num_std_12mts                      51296 non-null  int64
 37  num_sub                            51296 non-null  int64
 38  num_sub_6mts                       51296 non-null  int64
 39  num_sub_12mts                      51296 non-null  int64
 40  num_dbt                            51296 non-null  int64
 41  num_dbt_6mts                       51296 non-null  int64
 42  num_dbt_12mts                      51296 non-null  int64
 43  num_lss                            51296 non-null  int64
 44  num_lss_6mts                       51296 non-null  int64
 45  num_lss_12mts                      51296 non-null  int64
 46  recent_level_of_deliq              51296 non-null  int64
 47  tot_enq                            51296 non-null  float64
 48  CC_enq                             51296 non-null  float64
 49  CC_enq_L6m                         51296 non-null  float64
 50  CC_enq_L12m                        51296 non-null  float64
 51  PL_enq                             51296 non-null  float64
 52  PL_enq_L6m                         51296 non-null  float64
 53  PL_enq_L12m                        51296 non-null  float64
 54  time_since_recent_enq              51296 non-null  float64
 55  enq_L12m                           51296 non-null  float64
 56  enq_L6m                            51296 non-null  float64
 57  enq_L3m                            51296 non-null  float64
 58  MARITALSTATUS                      51296 non-null  object
 59  EDUCATION                          51296 non-null  object
 60  AGE                                51296 non-null  int64
 61  GENDER                             51296 non-null  object
 62  NETMONTHLYINCOME                   51296 non-null  int64
 63  Time_With_Curr_Empr                51296 non-null  int64
 64  pct_of_active_TLs_ever             51296 non-null  float64
 65  pct_opened_TLs_L6m_of_L12m         51296 non-null  float64
 66  pct_currentBal_all_TL              51296 non-null  float64
 67  CC_Flag                            51296 non-null  int64
 68  PL_Flag                            51296 non-null  int64
 69  pct_PL_enq_L6m_of_L12m             51296 non-null  float64
 70  pct_CC_enq_L6m_of_L12m             51296 non-null  float64
 71  pct_PL_enq_L6m_of_ever             51296 non-null  float64
 72  pct_CC_enq_L6m_of_ever             51296 non-null  float64
 73  HL_Flag                            51296 non-null  int64
 74  GL_Flag                            51296 non-null  int64
 75  last_prod_enq2                     51296 non-null  object
 76  first_prod_enq2                    51296 non-null  object
 77  Credit_Score                       51296 non-null  int64
 78  Approved_Flag                      51296 non-null  object
 79  time_since_recent_payment_missing  51296 non-null  int64
 80  time_since_recent_enq_missing      51296 non-null  int64
dtypes: float64(25), int64(50), object(6)
memory usage: 31.7+ MB

In [35]:
df.shape

(51296, 81)

## Feature selection

In [39]:
# check for categorical columns
categorical_column=[]

In [41]:
for i in df.columns:
    if (df[i].dtype=='object'):
        categorical_column.append(i)
        print(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [43]:
categorical_column

['MARITALSTATUS',
 'EDUCATION',
 'GENDER',
 'last_prod_enq2',
 'first_prod_enq2',
 'Approved_Flag']

In [48]:
for i in df.columns:
    for j in categorical_column:
        if i==j:
            print(df[j].value_counts())

MARITALSTATUS
Married    37724
Single     13572
Name: count, dtype: int64
EDUCATION
GRADUATE          16655
12TH              14458
SSC                9268
UNDER GRADUATE     5491
OTHERS             2915
POST-GRADUATE      2240
PROFESSIONAL        269
Name: count, dtype: int64
GENDER
M    45211
F     6085
Name: count, dtype: int64
last_prod_enq2
others          20808
ConsumerLoan    17782
PL               7955
CC               2338
AL               1511
HL                902
Name: count, dtype: int64
first_prod_enq2
others          28095
ConsumerLoan    11852
PL               4885
AL               2869
CC               2187
HL               1408
Name: count, dtype: int64
Approved_Flag
P2    32162
P3     7449
P4     5882
P1     5803
Name: count, dtype: int64

In [49]:
# Chi-square test
from scipy.stats import chi2_contingency
for i in ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
    chi2, pval, _, _ = chi2_contingency(pd.crosstab(df[i], df['Approved_Flag']))
    print(i, '---', pval)

MARITALSTATUS --- 2.7347247145640217e-257
EDUCATION --- 6.772122013692765e-38
GENDER --- 0.00025924146444508505
last_prod_enq2 --- 0.0
first_prod_enq2 --- 0.0

since all the categorical features have p-value less than 0.05, we will accept all the variable

In [50]:
# VIF for numerical columns
numeric_columns = []
for i in df.columns:
    if df[i].dtype != 'object' and i not in ['PROSPECTID','Approved_Flag']:
        numeric_columns.append(i)

In [51]:
len(numeric_columns)

74

In [52]:
# Selecting numerical features
numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()
vif_data = df[numeric_columns].copy()

# Set VIF threshold
vif_threshold = 6
columns_to_be_kept = []

In [54]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [55]:
while True:
    vif_values = [variance_inflation_factor(vif_data.values, i) for i in range(vif_data.shape[1])]
    vif_df = pd.DataFrame({"Feature": vif_data.columns, "VIF": vif_values})
    
    # Print VIF values
    print(vif_df.sort_values(by="VIF", ascending=False))
    
    max_vif = vif_df["VIF"].max()
    
    if max_vif < vif_threshold:
        break  # Stop if all VIFs are below threshold
    
    # Drop feature with highest VIF
    drop_feature = vif_df.loc[vif_df["VIF"] == max_vif, "Feature"].values[0]
    print(f"Dropping {drop_feature} with VIF: {max_vif}")
    vif_data.drop(columns=[drop_feature], inplace=True)

# Store final features with low VIF
columns_to_be_kept = vif_data.columns.tolist()

print("\nFinal Features with Low VIF:\n", columns_to_be_kept)

                  Feature       VIF
1                Total_TL       inf
2           Tot_Closed_TL       inf
3           Tot_Active_TL       inf
8           pct_active_tl       inf
20                  PL_TL       inf
..                    ...       ...
58                    AGE  1.403538
60    Time_With_Curr_Empr  1.266061
59       NETMONTHLYINCOME  1.055689
0              PROSPECTID  1.001334
63  pct_currentBal_all_TL  1.000982

[75 rows x 2 columns]
Dropping Total_TL with VIF: inf
                  Feature       VIF
1           Tot_Closed_TL       inf
2           Tot_Active_TL       inf
7           pct_active_tl       inf
19                  PL_TL       inf
20             Secured_TL       inf
..                    ...       ...
57                    AGE  1.403538
59    Time_With_Curr_Empr  1.266061
58       NETMONTHLYINCOME  1.055689
0              PROSPECTID  1.001334
62  pct_currentBal_all_TL  1.000982

[74 rows x 2 columns]
Dropping Tot_Closed_TL with VIF: inf
                  Feature       VIF
6           pct_active_tl       inf
17                Home_TL       inf
18                  PL_TL       inf
19             Secured_TL       inf
20           Unsecured_TL       inf
..                    ...       ...
56                    AGE  1.403538
58    Time_With_Curr_Empr  1.266061
57       NETMONTHLYINCOME  1.055689
0              PROSPECTID  1.001334
61  pct_currentBal_all_TL  1.000982

[73 rows x 2 columns]
Dropping pct_active_tl with VIF: inf
                  Feature       VIF
16                Home_TL       inf
17                  PL_TL       inf
18             Secured_TL       inf
19           Unsecured_TL       inf
12                Auto_TL       inf
..                    ...       ...
55                    AGE  1.403538
57    Time_With_Curr_Empr  1.266061
56       NETMONTHLYINCOME  1.055689
0              PROSPECTID  1.001334
60  pct_currentBal_all_TL  1.000982

[72 rows x 2 columns]
Dropping Auto_TL with VIF: inf
                   Feature          VIF
26         num_deliq_12mts          inf
27       num_deliq_6_12mts          inf
25          num_deliq_6mts          inf
57  pct_of_active_TLs_ever  2780.513877
6            pct_closed_tl  1872.003405
..                     ...          ...
54                     AGE     1.403538
56     Time_With_Curr_Empr     1.266061
55        NETMONTHLYINCOME     1.055689
0               PROSPECTID     1.001334
59   pct_currentBal_all_TL     1.000982

[71 rows x 2 columns]
Dropping num_deliq_6mts with VIF: inf
                   Feature          VIF
56  pct_of_active_TLs_ever  2780.513877
6            pct_closed_tl  1872.003405
17              Secured_TL    79.046764
14                 Gold_TL    57.859080
18            Unsecured_TL    36.343078
..                     ...          ...
53                     AGE     1.403538
55     Time_With_Curr_Empr     1.266061
54        NETMONTHLYINCOME     1.055689
0               PROSPECTID     1.001334
58   pct_currentBal_all_TL     1.000982

[70 rows x 2 columns]
Dropping pct_of_active_TLs_ever with VIF: 2780.5138769028167
                      Feature        VIF
17                 Secured_TL  95.767668
14                    Gold_TL  62.743606
18               Unsecured_TL  50.746764
22  time_since_recent_payment  36.785198
50                   enq_L12m  36.667519
..                        ...        ...
33               num_sub_6mts   2.548674
64                    HL_Flag   2.456854
35                    num_dbt   2.197480
32                    num_sub   1.567388
57      pct_currentBal_all_TL   1.001498

[69 rows x 2 columns]
Dropping Secured_TL with VIF: 95.7676683655289
                              Feature        VIF
21          time_since_recent_payment  36.759853
49                           enq_L12m  36.106105
65                       Credit_Score  34.857315
66  time_since_recent_payment_missing  30.847346
50                            enq_L6m  30.368700
..                                ...        ...
63                            HL_Flag   2.384113
34                            num_dbt   2.197137
14                            Gold_TL   2.077260
31                            num_sub   1.567164
56              pct_currentBal_all_TL   1.001470

[68 rows x 2 columns]
Dropping time_since_recent_payment with VIF: 36.75985329184405
                              Feature        VIF
48                           enq_L12m  36.105222
64                       Credit_Score  34.730154
49                            enq_L6m  30.366488
29                      num_std_12mts  25.617443
58             pct_PL_enq_L6m_of_L12m  24.854908
..                                ...        ...
33                            num_dbt   2.195684
14                            Gold_TL   2.072183
30                            num_sub   1.567108
65  time_since_recent_payment_missing   1.342846
55              pct_currentBal_all_TL   1.001470

[67 rows x 2 columns]
Dropping enq_L12m with VIF: 36.10522244664567
                              Feature        VIF
63                       Credit_Score  34.726289
29                      num_std_12mts  25.617439
57             pct_PL_enq_L6m_of_L12m  24.850884
59             pct_PL_enq_L6m_of_ever  23.935175
47              time_since_recent_enq  22.404304
..                                ...        ...
33                            num_dbt   2.195615
14                            Gold_TL   2.070952
30                            num_sub   1.566808
64  time_since_recent_payment_missing   1.341932
54              pct_currentBal_all_TL   1.001469

[66 rows x 2 columns]
Dropping Credit_Score with VIF: 34.726289262375914
                              Feature        VIF
29                      num_std_12mts  25.597852
57             pct_PL_enq_L6m_of_L12m  24.848419
59             pct_PL_enq_L6m_of_ever  23.900320
47              time_since_recent_enq  21.683084
7                Total_TL_opened_L12M  21.268642
..                                ...        ...
33                            num_dbt   2.195595
14                            Gold_TL   2.062850
30                            num_sub   1.566752
63  time_since_recent_payment_missing   1.335439
54              pct_currentBal_all_TL   1.001401

[65 rows x 2 columns]
Dropping num_std_12mts with VIF: 25.597851513189145
                              Feature        VIF
56             pct_PL_enq_L6m_of_L12m  24.847634
58             pct_PL_enq_L6m_of_ever  23.897625
46              time_since_recent_enq  21.683026
7                Total_TL_opened_L12M  21.267765
57             pct_CC_enq_L6m_of_L12m  19.969926
..                                ...        ...
32                            num_dbt   2.195549
14                            Gold_TL   2.047832
29                            num_sub   1.566722
62  time_since_recent_payment_missing   1.335438
53              pct_currentBal_all_TL   1.001385

[64 rows x 2 columns]
Dropping pct_PL_enq_L6m_of_L12m with VIF: 24.84763399387289
                              Feature        VIF
46              time_since_recent_enq  21.623950
7                Total_TL_opened_L12M  21.267661
56             pct_CC_enq_L6m_of_L12m  19.948190
58             pct_CC_enq_L6m_of_ever  18.029044
62      time_since_recent_enq_missing  17.667874
..                                ...        ...
32                            num_dbt   2.195544
14                            Gold_TL   2.047734
29                            num_sub   1.566658
61  time_since_recent_payment_missing   1.335280
53              pct_currentBal_all_TL   1.001384

[63 rows x 2 columns]
Dropping time_since_recent_enq with VIF: 21.623949811677406
                              Feature        VIF
7                Total_TL_opened_L12M  21.260405
55             pct_CC_enq_L6m_of_L12m  19.931673
57             pct_CC_enq_L6m_of_ever  18.026760
17                       Unsecured_TL  17.397060
1                       Tot_Active_TL  16.921298
..                                ...        ...
14                            Gold_TL   2.046886
29                            num_sub   1.566571
61      time_since_recent_enq_missing   1.389139
60  time_since_recent_payment_missing   1.334391
52              pct_currentBal_all_TL   1.001381

[62 rows x 2 columns]
Dropping Total_TL_opened_L12M with VIF: 21.260405188593246
                              Feature        VIF
54             pct_CC_enq_L6m_of_L12m  19.931641
56             pct_CC_enq_L6m_of_ever  18.026731
16                       Unsecured_TL  17.376722
45                            enq_L6m  16.479449
24                  num_times_30p_dpd  14.523771
..                                ...        ...
13                            Gold_TL   2.037477
28                            num_sub   1.566513
60      time_since_recent_enq_missing   1.389138
59  time_since_recent_payment_missing   1.333373
51              pct_currentBal_all_TL   1.001363

[61 rows x 2 columns]
Dropping pct_CC_enq_L6m_of_L12m with VIF: 19.9316407791546
                              Feature        VIF
16                       Unsecured_TL  17.375358
45                            enq_L6m  16.476362
24                  num_times_30p_dpd  14.523368
47                                AGE  13.068203
1                       Tot_Active_TL  12.873975
38                            tot_enq  12.864132
44                        PL_enq_L12m  12.456571
12                        Consumer_TL  11.621227
43                         PL_enq_L6m  10.717386
42                             PL_enq   9.496672
41                        CC_enq_L12m   9.306915
33                      num_dbt_12mts   9.303887
7                  Tot_TL_closed_L12M   8.961307
25                  num_times_60p_dpd   8.444522
22                    num_deliq_12mts   8.145021
20               num_times_delinquent   8.002778
3                   Tot_TL_closed_L6M   7.951840
36                      num_lss_12mts   7.949502
40                         CC_enq_L6m   7.905899
4                     pct_tl_open_L6M   7.753700
50         pct_opened_TLs_L6m_of_L12m   7.441436
32                       num_dbt_6mts   7.384828
6                       pct_closed_tl   7.350466
23                  num_deliq_6_12mts   6.883474
46                            enq_L3m   6.680007
39                             CC_enq   6.597649
35                       num_lss_6mts   6.355173
2                 Total_TL_opened_L6M   6.190501
9                  pct_tl_closed_L12M   5.873858
21          max_recent_level_of_deliq   5.416381
18                      Age_Oldest_TL   5.005398
37              recent_level_of_deliq   4.945040
26                            num_std   4.779459
5                   pct_tl_closed_L6M   4.766267
14                            Home_TL   4.451959
57                            GL_Flag   4.403055
8                    pct_tl_open_L12M   4.361031
11                              CC_TL   4.306027
49                Time_With_Curr_Empr   3.939855
15                              PL_TL   3.882145
27                       num_std_6mts   3.857737
0                          PROSPECTID   3.634483
52                            CC_Flag   3.191987
30                      num_sub_12mts   3.103750
19                      Age_Newest_TL   2.990916
17                           Other_TL   2.960039
10                    Tot_Missed_Pmnt   2.838438
48                   NETMONTHLYINCOME   2.807908
53                            PL_Flag   2.794960
34                            num_lss   2.727610
29                       num_sub_6mts   2.547097
56                            HL_Flag   2.374831
54             pct_PL_enq_L6m_of_ever   2.298438
55             pct_CC_enq_L6m_of_ever   2.276183
31                            num_dbt   2.194951
13                            Gold_TL   2.037267
28                            num_sub   1.566510
59      time_since_recent_enq_missing   1.389029
58  time_since_recent_payment_missing   1.333371
51              pct_currentBal_all_TL   1.001362
Dropping Unsecured_TL with VIF: 17.375357719609855
                              Feature        VIF
44                            enq_L6m  16.464091
23                  num_times_30p_dpd  14.522532
46                                AGE  13.065582
37                            tot_enq  12.713950
43                        PL_enq_L12m  12.452370
1                       Tot_Active_TL  12.294716
42                         PL_enq_L6m  10.714086
41                             PL_enq   9.437607
40                        CC_enq_L12m   9.306017
32                      num_dbt_12mts   9.302184
7                  Tot_TL_closed_L12M   8.944867
24                  num_times_60p_dpd   8.442630
21                    num_deliq_12mts   8.144716
19               num_times_delinquent   8.002376
35                      num_lss_12mts   7.949093
39                         CC_enq_L6m   7.902181
3                   Tot_TL_closed_L6M   7.897723
4                     pct_tl_open_L6M   7.748868
49         pct_opened_TLs_L6m_of_L12m   7.434187
31                       num_dbt_6mts   7.383956
6                       pct_closed_tl   7.348758
22                  num_deliq_6_12mts   6.882065
45                            enq_L3m   6.678853
38                             CC_enq   6.592742
34                       num_lss_6mts   6.355156
2                 Total_TL_opened_L6M   6.190489
9                  pct_tl_closed_L12M   5.868870
20          max_recent_level_of_deliq   5.416149
17                      Age_Oldest_TL   4.997925
36              recent_level_of_deliq   4.945027
25                            num_std   4.766533
5                   pct_tl_closed_L6M   4.761944
14                            Home_TL   4.450388
56                            GL_Flag   4.403049
8                    pct_tl_open_L12M   4.356131
11                              CC_TL   4.072061
48                Time_With_Curr_Empr   3.939839
12                        Consumer_TL   3.878759
26                       num_std_6mts   3.857708
0                          PROSPECTID   3.634002
51                            CC_Flag   3.191967
29                      num_sub_12mts   3.103636
15                              PL_TL   3.039814
18                      Age_Newest_TL   2.990900
10                    Tot_Missed_Pmnt   2.830511
47                   NETMONTHLYINCOME   2.807906
52                            PL_Flag   2.793735
33                            num_lss   2.727289
16                           Other_TL   2.558757
28                       num_sub_6mts   2.546995
55                            HL_Flag   2.373180
53             pct_PL_enq_L6m_of_ever   2.298413
54             pct_CC_enq_L6m_of_ever   2.275739
30                            num_dbt   2.194870
13                            Gold_TL   2.030076
27                            num_sub   1.566378
58      time_since_recent_enq_missing   1.388759
57  time_since_recent_payment_missing   1.333100
50              pct_currentBal_all_TL   1.001309
Dropping enq_L6m with VIF: 16.464090921398267
                              Feature        VIF
23                  num_times_30p_dpd  14.517610
45                                AGE  13.059512
43                        PL_enq_L12m  12.422622
1                       Tot_Active_TL  12.238401
42                         PL_enq_L6m   9.494975
40                        CC_enq_L12m   9.303501
32                      num_dbt_12mts   9.302116
37                            tot_enq   9.255971
7                  Tot_TL_closed_L12M   8.916769
41                             PL_enq   8.908779
24                  num_times_60p_dpd   8.442427
21                    num_deliq_12mts   8.143747
19               num_times_delinquent   7.986348
35                      num_lss_12mts   7.948922
3                   Tot_TL_closed_L6M   7.897682
4                     pct_tl_open_L6M   7.711211
39                         CC_enq_L6m   7.680618
48         pct_opened_TLs_L6m_of_L12m   7.434185
31                       num_dbt_6mts   7.383789
6                       pct_closed_tl   7.339597
22                  num_deliq_6_12mts   6.882028
38                             CC_enq   6.372780
34                       num_lss_6mts   6.355137
2                 Total_TL_opened_L6M   5.972034
9                  pct_tl_closed_L12M   5.865614
20          max_recent_level_of_deliq   5.416146
17                      Age_Oldest_TL   4.986900
36              recent_level_of_deliq   4.945018
5                   pct_tl_closed_L6M   4.761863
25                            num_std   4.755197
14                            Home_TL   4.448555
55                            GL_Flag   4.403012
8                    pct_tl_open_L12M   4.353853
11                              CC_TL   4.071784
47                Time_With_Curr_Empr   3.939740
12                        Consumer_TL   3.867962
26                       num_std_6mts   3.853519
0                          PROSPECTID   3.633999
44                            enq_L3m   3.299328
50                            CC_Flag   3.191966
29                      num_sub_12mts   3.103625
15                              PL_TL   3.034966
18                      Age_Newest_TL   2.983695
10                    Tot_Missed_Pmnt   2.825688
46                   NETMONTHLYINCOME   2.807682
51                            PL_Flag   2.792507
33                            num_lss   2.727255
16                           Other_TL   2.558052
28                       num_sub_6mts   2.546931
54                            HL_Flag   2.370515
52             pct_PL_enq_L6m_of_ever   2.296165
53             pct_CC_enq_L6m_of_ever   2.275708
30                            num_dbt   2.194844
13                            Gold_TL   2.027551
27                            num_sub   1.566376
57      time_since_recent_enq_missing   1.387937
56  time_since_recent_payment_missing   1.332911
49              pct_currentBal_all_TL   1.001305
Dropping num_times_30p_dpd with VIF: 14.51761036970465
                              Feature        VIF
44                                AGE  13.059475
42                        PL_enq_L12m  12.420867
1                       Tot_Active_TL  12.230601
41                         PL_enq_L6m   9.494513
39                        CC_enq_L12m   9.302414
31                      num_dbt_12mts   9.301436
36                            tot_enq   9.255546
7                  Tot_TL_closed_L12M   8.916401
40                             PL_enq   8.908693
21                    num_deliq_12mts   8.067782
34                      num_lss_12mts   7.948774
3                   Tot_TL_closed_L6M   7.897581
4                     pct_tl_open_L6M   7.710603
38                         CC_enq_L6m   7.680426
47         pct_opened_TLs_L6m_of_L12m   7.433794
30                       num_dbt_6mts   7.383618
6                       pct_closed_tl   7.339581
22                  num_deliq_6_12mts   6.881317
37                             CC_enq   6.372622
33                       num_lss_6mts   6.355017
2                 Total_TL_opened_L6M   5.970588
9                  pct_tl_closed_L12M   5.865261
20          max_recent_level_of_deliq   5.409979
17                      Age_Oldest_TL   4.986746
35              recent_level_of_deliq   4.945018
19               num_times_delinquent   4.783096
5                   pct_tl_closed_L6M   4.761721
24                            num_std   4.754629
14                            Home_TL   4.448457
54                            GL_Flag   4.402857
8                    pct_tl_open_L12M   4.353501
11                              CC_TL   4.070451
46                Time_With_Curr_Empr   3.939527
12                        Consumer_TL   3.867383
25                       num_std_6mts   3.853114
0                          PROSPECTID   3.633973
43                            enq_L3m   3.299322
49                            CC_Flag   3.191726
28                      num_sub_12mts   3.103612
15                              PL_TL   3.033138
18                      Age_Newest_TL   2.983659

In [56]:
len(columns_to_be_kept)

47

In [57]:
# check Anova for columns_to_be_kept 

from scipy.stats import f_oneway

columns_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])  
    b = list(df['Approved_Flag'])  
    
    group_P1 = [value for value, group in zip(a, b) if group == 'P1']
    group_P2 = [value for value, group in zip(a, b) if group == 'P2']
    group_P3 = [value for value, group in zip(a, b) if group == 'P3']
    group_P4 = [value for value, group in zip(a, b) if group == 'P4']


    f_statistic, p_value = f_oneway(group_P1, group_P2, group_P3, group_P4)

    if p_value <= 0.05:
        columns_to_be_kept_numerical.append(i)

In [58]:
len(columns_to_be_kept_numerical)

43

In [59]:
columns_to_be_kept_numerical

['PROSPECTID',
 'Total_TL_opened_L6M',
 'Tot_TL_closed_L6M',
 'pct_tl_closed_L6M',
 'pct_closed_tl',
 'pct_tl_open_L12M',
 'pct_tl_closed_L12M',
 'Tot_Missed_Pmnt',
 'CC_TL',
 'Consumer_TL',
 'Gold_TL',
 'Home_TL',
 'PL_TL',
 'Other_TL',
 'Age_Oldest_TL',
 'Age_Newest_TL',
 'num_times_delinquent',
 'max_recent_level_of_deliq',
 'num_deliq_6_12mts',
 'num_times_60p_dpd',
 'num_std',
 'num_std_6mts',
 'num_sub',
 'num_sub_12mts',
 'num_dbt',
 'num_lss',
 'recent_level_of_deliq',
 'CC_enq',
 'CC_enq_L6m',
 'PL_enq',
 'PL_enq_L6m',
 'enq_L3m',
 'NETMONTHLYINCOME',
 'Time_With_Curr_Empr',
 'pct_opened_TLs_L6m_of_L12m',
 'CC_Flag',
 'PL_Flag',
 'pct_PL_enq_L6m_of_ever',
 'pct_CC_enq_L6m_of_ever',
 'HL_Flag',
 'GL_Flag',
 'time_since_recent_payment_missing',
 'time_since_recent_enq_missing']

In [60]:
df.shape

(51296, 81)

In [61]:
# listing all the final features
features = columns_to_be_kept_numerical + ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']
df = df[features + ['Approved_Flag']]

In [62]:
df.shape

(51296, 49)

## Feature engineering

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
from imblearn.over_sampling import SMOTENC

In [66]:
test_size = 0.2   # load from params.yaml
random_state = 42

In [128]:
df['Approved_Flag'].value_counts()

Approved_Flag
1    32162
2     7449
3     5882
0     5803
Name: count, dtype: int64

In [68]:
# 1. Encode target
label_encoder = LabelEncoder()
df['Approved_Flag'] = label_encoder.fit_transform(df['Approved_Flag'])

X = df.drop(columns=['Approved_Flag'])
y = df['Approved_Flag']

In [69]:
# 2. Split FIRST
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=test_size, stratify=y, random_state=random_state
)

In [70]:
categorical_cols = ['EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2', 'MARITALSTATUS']

In [71]:
encoder = OrdinalEncoder()

X_train[categorical_cols] = encoder.fit_transform(X_train[categorical_cols])
X_test[categorical_cols] = encoder.transform(X_test[categorical_cols])

In [72]:
categorical_indices = [X_train.columns.get_loc(col) for col in categorical_cols]

In [73]:
# 6. SMOTENC (ONLY on train)
smote_nc = SMOTENC(
    categorical_features=categorical_indices,
    random_state=random_state
)

In [74]:
X_train_resampled, y_train_resampled = smote_nc.fit_resample(X_train, y_train)

In [75]:
train_final_df = pd.concat(
    [pd.DataFrame(X_train_resampled, columns=X_train.columns),
     pd.Series(y_train_resampled, name='Approved_Flag')],
    axis=1
)

In [77]:
train_final_df.shape

(102916, 49)

In [79]:
train_final_df['Approved_Flag'].value_counts()

Approved_Flag
0    25729
1    25729
2    25729
3    25729
Name: count, dtype: int64

In [80]:
test_final_df = pd.concat(
    [X_test.reset_index(drop=True),
     y_test.reset_index(drop=True)],
    axis=1
)

In [81]:
test_final_df.shape

(10260, 49)

In [82]:
test_final_df['Approved_Flag'].value_counts()

Approved_Flag
1    6433
2    1490
3    1176
0    1161
Name: count, dtype: int64

In [92]:
X_train = train_final_df.drop('Approved_Flag', axis=1)
y_train = train_final_df['Approved_Flag']

X_test = test_final_df.drop('Approved_Flag', axis=1)
y_test = test_final_df['Approved_Flag']

class_names = ['p1', 'p2', 'p3', 'p4']

In [93]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, f1_score

def evaluate_model(name, model, X_train, y_train, X_test, y_test):
    
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    precision, recall, f1_vals, _ = precision_recall_fscore_support(y_test, y_pred)
    
    f1_weighted = f1_score(y_test, y_pred, average='weighted')
    f1_macro = f1_score(y_test, y_pred, average='macro')
    
    print(f"\n===== {name} =====")
    print(f"Accuracy: {accuracy}")
    print(f"F1 Weighted: {f1_weighted}")
    print(f"F1 Macro: {f1_macro}\n")
    
    for i, v in enumerate(class_names):
        print(f"Class {v}:")
        print(f"Precision: {precision[i]}")
        print(f"Recall: {recall[i]}")
        print(f"F1 Score: {f1_vals[i]}")
        print()
    
    return {
        "model": model,
        "accuracy": accuracy,
        "f1_weighted": f1_weighted,
        "f1_macro": f1_macro,
        "class_f1": f1_vals
    }

In [94]:
from sklearn.ensemble import RandomForestClassifier

baseline_result = evaluate_model(
    "Random Forest (Baseline)",
    RandomForestClassifier(random_state=42),
    X_train, y_train, X_test, y_test
)

===== Random Forest (Baseline) =====
Accuracy: 0.7653021442495127
F1 Weighted: 0.7571222083845277
F1 Macro: 0.6705124675399027

Class p1:
Precision: 0.7005856515373353
Recall: 0.8242894056847545
F1 Score: 0.7574198654531065

Class p2:
Precision: 0.8446382914724019
Recall: 0.8729986009637805
F1 Score: 0.8585843143250268

Class p3:
Precision: 0.41181657848324515
Recall: 0.31342281879194633
F1 Score: 0.3559451219512195

Class p4:
Precision: 0.7308730873087309
Recall: 0.6904761904761905
F1 Score: 0.7101005684302579

In [95]:
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

models = {
    "XGBoost": XGBClassifier(objective='multi:softprob', eval_metric='mlogloss'),
    "CatBoost": CatBoostClassifier(verbose=0),
    "LightGBM": LGBMClassifier()
}

results = []

for name, model in models.items():
    res = evaluate_model(name, model, X_train, y_train, X_test, y_test)
    results.append(res)

===== XGBoost =====
Accuracy: 0.7807992202729045
F1 Weighted: 0.768912412883016
F1 Macro: 0.6834505367211032

Class p1:
Precision: 0.7489812550937245
Recall: 0.7915590008613265
F1 Score: 0.7696817420435511

Class p2:
Precision: 0.8423429986886202
Recall: 0.8986475983211565
F1 Score: 0.8695848375451264

Class p3:
Precision: 0.4542713567839196
Recall: 0.30335570469798656
F1 Score: 0.3637826961770624

Class p4:
Precision: 0.731063829787234
Recall: 0.7304421768707483
F1 Score: 0.7307528711186729


===== CatBoost =====
Accuracy: 0.7780701754385965
F1 Weighted: 0.768705344428023
F1 Macro: 0.6846534613700939

Class p1:
Precision: 0.7467637540453075
Recall: 0.7950043066322137
F1 Score: 0.7701293283270755

Class p2:
Precision: 0.8456771909117734
Recall: 0.89103062334836
F1 Score: 0.8677617137234123

Class p3:
Precision: 0.4357338195077484
Recall: 0.3208053691275168
F1 Score: 0.3695400077309625

Class p4:
Precision: 0.7397737162750218
Recall: 0.7227891156462585
F1 Score: 0.7311827956989247

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.579280 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5565
[LightGBM] [Info] Number of data points in the train set: 102916, number of used features: 48
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294

===== LightGBM =====
Accuracy: 0.7799220272904483
F1 Weighted: 0.7679230712939642
F1 Macro: 0.6844749351874803

Class p1:
Precision: 0.7558799675587997
Recall: 0.8027562446167097
F1 Score: 0.7786131996658312

Class p2:
Precision: 0.8398369248689574
Recall: 0.8966267682263329
F1 Score: 0.867303210284941

Class p3:
Precision: 0.4411177644710579
Recall: 0.2966442953020134
F1 Score: 0.3547351524879615

Class p4:
Precision: 0.7433016421780466
Recall: 0.7312925170068028
F1 Score: 0.7372481783111873

In [100]:
model_names = list(models.keys())

for i, res in enumerate(results):
    res['name'] = model_names[i]

In [102]:
best_result = max(
    results,
    key=lambda x: (x['f1_macro'], min(x['class_f1']))
)

print("\n===== BEST MODEL =====")
print("Model Name:", best_result['name'])   # ✅ ADD THIS
print("F1 Weighted:", best_result['f1_weighted'])
print("F1 Macro:", best_result['f1_macro'])

===== BEST MODEL =====
Model Name: CatBoost
F1 Weighted: 0.768705344428023
F1 Macro: 0.6846534613700939

In [126]:
fast_model = CatBoostClassifier(
    iterations=300,          
    depth=5,                 
    learning_rate=0.05,     
    l2_leaf_reg=5,           
    class_weights=[1, 1, 1.6, 1],
    verbose=0
)

fast_model.fit(X_train, y_train)

CatBoostClassifier(class_weights=[1, 1, 1.6, 1], depth=5, iterations=300, l2_leaf_reg=5, learning_rate=0.05, verbose=0)

In [127]:
evaluate_model(
    "Final catboost",
    fast_model,
    X_train, y_train, X_test, y_test
)

===== Final catboost =====
Accuracy: 0.752729044834308
F1 Weighted: 0.7617066977859407
F1 Macro: 0.6883795790615082

Class p1:
Precision: 0.6985294117647058
Recall: 0.818260120585702
F1 Score: 0.753669178897263

Class p2:
Precision: 0.8772780471493061
Recall: 0.8156381159645577
F1 Score: 0.8453359110681489

Class p3:
Precision: 0.39823008849557523
Recall: 0.5436241610738255
F1 Score: 0.45970488081725314

Class p4:
Precision: 0.8090395480225989
Recall: 0.608843537414966
F1 Score: 0.6948083454633673

{'model': CatBoostClassifier(class_weights=[1, 1, 1.6, 1], depth=5, iterations=300, l2_leaf_reg=5, learning_rate=0.05, verbose=0),
 'accuracy': 0.752729044834308,
 'f1_weighted': 0.7617066977859407,
 'f1_macro': 0.6883795790615082,
 'class_f1': array([0.75366918, 0.84533591, 0.45970488, 0.69480835])}